// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: chatService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomRequest_Action int32

const (
	RoomRequest_CREATE RoomRequest_Action = 0
	RoomRequest_JOIN   RoomRequest_Action = 1
	RoomRequest_LEAVE  RoomRequest_Action = 2
)

// Enum value maps for RoomRequest_Action.
var (
	RoomRequest_Action_name = map[int32]string{
		0: "CREATE",
		1: "JOIN",
		2: "LEAVE",
	}
	RoomRequest_Action_value = map[string]int32{
		"CREATE": 0,
		"JOIN":   1,
		"LEAVE":  2,
	}
)

func (x RoomRequest_Action) Enum() *RoomRequest_Action {
	p := new(RoomRequest_Action)
	*p = x
	return p
}

func (x RoomRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_chatService_proto_enumTypes[0].Descriptor()
}

func (RoomRequest_Action) Type() protoreflect.EnumType {
	return &file_chatService_proto_enumTypes[0]
}

func (x RoomRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomRequest_Action.Descriptor instead.
func (RoomRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{2, 0}
}

type RoomResponse_Status int32

const (
	RoomResponse_SUCCESS RoomResponse_Status = 0
	RoomResponse_FAILURE RoomResponse_Status = 1
)

// Enum value maps for RoomResponse_Status.
var (
	RoomResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	RoomResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x RoomResponse_Status) Enum() *RoomResponse_Status {
	p := new(RoomResponse_Status)
	*p = x
	return p
}

func (x RoomResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_chatService_proto_enumTypes[1].Descriptor()
}

func (RoomResponse_Status) Type() protoreflect.EnumType {
	return &file_chatService_proto_enumTypes[1]
}

func (x RoomResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomResponse_Status.Descriptor instead.
func (RoomResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{3, 0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId    string `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	User      *User  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   string     `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Name     string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members  []*User    `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Messages []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetMembers() []*User {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Room) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 채팅룸 관련 요청 메시지
type RoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   *User              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Action RoomRequest_Action `protobuf:"varint,2,opt,name=action,proto3,enum=lavumi.RoomRequest_Action" json:"action,omitempty"`
	Room   *Room              `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{2}
}

func (x *RoomRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RoomRequest) GetAction() RoomRequest_Action {
	if x != nil {
		return x.Action
	}
	return RoomRequest_CREATE
}

func (x *RoomRequest) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// 채팅룸 관련 응답 메시지
type RoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  RoomResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=lavumi.RoomResponse_Status" json:"status,omitempty"`
	Message string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Room    *Room               `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{3}
}

func (x *RoomResponse) GetStatus() RoomResponse_Status {
	if x != nil {
		return x.Status
	}
	return RoomResponse_SUCCESS
}

func (x *RoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type RoomList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomList []*Room `protobuf:"bytes,1,rep,name=room_list,json=roomList,proto3" json:"room_list,omitempty"`
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{4}
}

func (x *RoomList) GetRoomList() []*Room {
	if x != nil {
		return x.RoomList
	}
	return nil
}

type Close struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Close) Reset() {
	*x = Close{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_chatService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_chatService_proto_rawDescGZIP(), []int{5}
}

var File_chatService_proto protoreflect.FileDescriptor

var file_chatService_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x1a, 0x10, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x87, 0x01, 0x0a, 0x04, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x61, 0x76, 0x75,
	0x6d, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d,
	0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x29, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x02, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d,
	0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x22, 0x35, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x09, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c,
	0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x32, 0xd7, 0x02,
	0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x6c,
	0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d,
	0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x13, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d,
	0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x32, 0x0a, 0x10, 0x42,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x0f, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x0d, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x13, 0x2e, 0x6c,
	0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatService_proto_rawDescOnce sync.Once
	file_chatService_proto_rawDescData = file_chatService_proto_rawDesc
)

func file_chatService_proto_rawDescGZIP() []byte {
	file_chatService_proto_rawDescOnce.Do(func() {
		file_chatService_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatService_proto_rawDescData)
	})
	return file_chatService_proto_rawDescData
}

var file_chatService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatService_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chatService_proto_goTypes = []interface{}{
	(RoomRequest_Action)(0),  // 0: lavumi.RoomRequest.Action
	(RoomResponse_Status)(0), // 1: lavumi.RoomResponse.Status
	(*Message)(nil),          // 2: lavumi.Message
	(*Room)(nil),             // 3: lavumi.Room
	(*RoomRequest)(nil),      // 4: lavumi.RoomRequest
	(*RoomResponse)(nil),     // 5: lavumi.RoomResponse
	(*RoomList)(nil),         // 6: lavumi.RoomList
	(*Close)(nil),            // 7: lavumi.Close
	(*User)(nil),             // 8: lavumi.User
}
var file_chatService_proto_depIdxs = []int32{
	8,  // 0: lavumi.Message.user:type_name -> lavumi.User
	8,  // 1: lavumi.Room.members:type_name -> lavumi.User
	2,  // 2: lavumi.Room.messages:type_name -> lavumi.Message
	8,  // 3: lavumi.RoomRequest.user:type_name -> lavumi.User
	0,  // 4: lavumi.RoomRequest.action:type_name -> lavumi.RoomRequest.Action
	3,  // 5: lavumi.RoomRequest.room:type_name -> lavumi.Room
	1,  // 6: lavumi.RoomResponse.status:type_name -> lavumi.RoomResponse.Status
	3,  // 7: lavumi.RoomResponse.room:type_name -> lavumi.Room
	3,  // 8: lavumi.RoomList.room_list:type_name -> lavumi.Room
	4,  // 9: lavumi.RoomService.GetRoomList:input_type -> lavumi.RoomRequest
	4,  // 10: lavumi.RoomService.CreateRoom:input_type -> lavumi.RoomRequest
	4,  // 11: lavumi.RoomService.JoinRoom:input_type -> lavumi.RoomRequest
	4,  // 12: lavumi.RoomService.CreateStream:input_type -> lavumi.RoomRequest
	2,  // 13: lavumi.RoomService.BroadcastMessage:input_type -> lavumi.Message
	4,  // 14: lavumi.RoomService.LeaveRoom:input_type -> lavumi.RoomRequest
	6,  // 15: lavumi.RoomService.GetRoomList:output_type -> lavumi.RoomList
	5,  // 16: lavumi.RoomService.CreateRoom:output_type -> lavumi.RoomResponse
	5,  // 17: lavumi.RoomService.JoinRoom:output_type -> lavumi.RoomResponse
	2,  // 18: lavumi.RoomService.CreateStream:output_type -> lavumi.Message
	7,  // 19: lavumi.RoomService.BroadcastMessage:output_type -> lavumi.Close
	5,  // 20: lavumi.RoomService.LeaveRoom:output_type -> lavumi.RoomResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chatService_proto_init() }
func file_chatService_proto_init() {
	if File_chatService_proto != nil {
		return
	}
	file_types_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chatService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Close); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatService_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatService_proto_goTypes,
		DependencyIndexes: file_chatService_proto_depIdxs,
		EnumInfos:         file_chatService_proto_enumTypes,
		MessageInfos:      file_chatService_proto_msgTypes,
	}.Build()
	File_chatService_proto = out.File
	file_chatService_proto_rawDesc = nil
	file_chatService_proto_goTypes = nil
	file_chatService_proto_depIdxs = nil
}
