// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: loginService.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest_Type int32

const (
	LoginRequest_APPLE  LoginRequest_Type = 0
	LoginRequest_GOOGLE LoginRequest_Type = 1
	LoginRequest_GUEST  LoginRequest_Type = 2
)

// Enum value maps for LoginRequest_Type.
var (
	LoginRequest_Type_name = map[int32]string{
		0: "APPLE",
		1: "GOOGLE",
		2: "GUEST",
	}
	LoginRequest_Type_value = map[string]int32{
		"APPLE":  0,
		"GOOGLE": 1,
		"GUEST":  2,
	}
)

func (x LoginRequest_Type) Enum() *LoginRequest_Type {
	p := new(LoginRequest_Type)
	*p = x
	return p
}

func (x LoginRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_loginService_proto_enumTypes[0].Descriptor()
}

func (LoginRequest_Type) Type() protoreflect.EnumType {
	return &file_loginService_proto_enumTypes[0]
}

func (x LoginRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginRequest_Type.Descriptor instead.
func (LoginRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_loginService_proto_rawDescGZIP(), []int{0, 0}
}

type LoginResponse_Status int32

const (
	LoginResponse_SUCCESS LoginResponse_Status = 0
	LoginResponse_FAILURE LoginResponse_Status = 1
)

// Enum value maps for LoginResponse_Status.
var (
	LoginResponse_Status_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	LoginResponse_Status_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x LoginResponse_Status) Enum() *LoginResponse_Status {
	p := new(LoginResponse_Status)
	*p = x
	return p
}

func (x LoginResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_loginService_proto_enumTypes[1].Descriptor()
}

func (LoginResponse_Status) Type() protoreflect.EnumType {
	return &file_loginService_proto_enumTypes[1]
}

func (x LoginResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_Status.Descriptor instead.
func (LoginResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_loginService_proto_rawDescGZIP(), []int{1, 0}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginType     LoginRequest_Type `protobuf:"varint,1,opt,name=loginType,proto3,enum=lavumi.LoginRequest_Type" json:"loginType,omitempty"`
	PlatformId    string            `protobuf:"bytes,2,opt,name=platformId,proto3" json:"platformId,omitempty"`
	PlatformToken string            `protobuf:"bytes,3,opt,name=platformToken,proto3" json:"platformToken,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loginService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loginService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_loginService_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLoginType() LoginRequest_Type {
	if x != nil {
		return x.LoginType
	}
	return LoginRequest_APPLE
}

func (x *LoginRequest) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *LoginRequest) GetPlatformToken() string {
	if x != nil {
		return x.PlatformToken
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status LoginResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=lavumi.LoginResponse_Status" json:"status,omitempty"`
	User   *User                `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loginService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loginService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_loginService_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetStatus() LoginResponse_Status {
	if x != nil {
		return x.Status
	}
	return LoginResponse_SUCCESS
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_loginService_proto protoreflect.FileDescriptor

var file_loginService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x1a, 0x10, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7,
	0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x28,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x50, 0x50, 0x4c, 0x45, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f, 0x4f, 0x47, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6c, 0x61, 0x76,
	0x75, 0x6d, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49,
	0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x32, 0x44, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x14, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x61, 0x76, 0x75, 0x6d, 0x69, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_loginService_proto_rawDescOnce sync.Once
	file_loginService_proto_rawDescData = file_loginService_proto_rawDesc
)

func file_loginService_proto_rawDescGZIP() []byte {
	file_loginService_proto_rawDescOnce.Do(func() {
		file_loginService_proto_rawDescData = protoimpl.X.CompressGZIP(file_loginService_proto_rawDescData)
	})
	return file_loginService_proto_rawDescData
}

var file_loginService_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_loginService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loginService_proto_goTypes = []interface{}{
	(LoginRequest_Type)(0),    // 0: lavumi.LoginRequest.Type
	(LoginResponse_Status)(0), // 1: lavumi.LoginResponse.Status
	(*LoginRequest)(nil),      // 2: lavumi.LoginRequest
	(*LoginResponse)(nil),     // 3: lavumi.LoginResponse
	(*User)(nil),              // 4: lavumi.User
}
var file_loginService_proto_depIdxs = []int32{
	0, // 0: lavumi.LoginRequest.loginType:type_name -> lavumi.LoginRequest.Type
	1, // 1: lavumi.LoginResponse.status:type_name -> lavumi.LoginResponse.Status
	4, // 2: lavumi.LoginResponse.user:type_name -> lavumi.User
	2, // 3: lavumi.LoginService.Login:input_type -> lavumi.LoginRequest
	3, // 4: lavumi.LoginService.Login:output_type -> lavumi.LoginResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_loginService_proto_init() }
func file_loginService_proto_init() {
	if File_loginService_proto != nil {
		return
	}
	file_types_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_loginService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loginService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loginService_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loginService_proto_goTypes,
		DependencyIndexes: file_loginService_proto_depIdxs,
		EnumInfos:         file_loginService_proto_enumTypes,
		MessageInfos:      file_loginService_proto_msgTypes,
	}.Build()
	File_loginService_proto = out.File
	file_loginService_proto_rawDesc = nil
	file_loginService_proto_goTypes = nil
	file_loginService_proto_depIdxs = nil
}
